/*DEPARTAMENTO*
INSERT INTO DEPTO (CD_DEPTO, NM_DEPTO, CD_GERENTE, CD_DEPTO_CTB) VALUES ('ELA','BRUNAGARCIA', 100321, 'ELE');/

/*FUNCIONARIO*
INSERT INTO FUNC (CD_MAT, NM_FUNC, NM_SOBRENOME, VL_SAL, CD_DEPTO, IN_SEXO, NR_CARGO) VALUES (1,'JOANA', 'RODRIGUES', 1435, 'ELA', 'F', 52); 
INSERT INTO FUNC (CD_MAT, NM_FUNC, NM_SOBRENOME, VL_SAL, CD_DEPTO, IN_SEXO, NR_CARGO) VALUES (2,'MARCELO', 'SALGADO', 1743, 'ELA', 'M', 55);
INSERT INTO FUNC (CD_MAT, NM_FUNC, NM_SOBRENOME, CD_DEPTO, NR_RAMAL, DT_ADM, NR_CARGO, NR_RG, IN_SEXO, DT_NASC, VL_SAL, NM_FOTO)VALUES (2026, 'ANA', 'GOMES', 'ELA', 2222, '2015-09-09', 20, 3591013, 'F', '2007-10-14', 1200, NULL);/

/*ATIV*
INSERT INTO ATIV (CD_ATIV, NM_SIGLA, TX_DESCRICAO) VALUES (234, 'BRUNA12', 'FILOSOFIA');/

/*PROJETO*
INSERT INTO PROJ (CD_PROJ, NM_PROJ, CD_DEPTO, QT_EQP, DT_INI, DT_FIM) VALUES ('ANAGMS', 'INFORMATICA', 'ELA', 23, '2024-10-05', '2024-10-06');/

/*PROJ ATIVIDADE*
INSERT INTO PROJETO_ATIVIDADE (CD_PROJ, CD_ATIV, DT_INI, DT_FIM) VALUES ('ANAGMS', 234 , '2024-10-04', '2024-10-08');/

/*HST PROMO
INSERT INTO HST_PROMO (CD_MAT, CD_DEPTO, DT_PROMOCAO, VL_SAL, NR_CARGO, TX_MOTIVO) VALUES (1, 'ELA', '2024-10-02', 2100, 63, 'ESFORÇO E DEDICAÇÃO AO TRABALHO');*/
